/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-tertiary-container": "#9da6ab",
        "primary-fixed": "#E5D5F0",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#dbe4e9",
        "on-secondary-fixed-variant": "#381E57",
        "on-tertiary": "#ffffff",
        "primary": "#9A7DB8",
        "tertiary-fixed-dim": "#bfc8cd",
        "on-primary-container": "#EAE0F5",
        "error": "#ba1a1a",
        "surface": "#FAF7FC",
        "inverse-on-surface": "#F5EFF9",
        "on-surface-variant": "#4E4259",
        "surface-dim": "#D9C7E6",
        "on-primary-fixed-variant": "#5C3C7B",
        "surface-container": "#F3EBF7",
        "on-secondary-container": "#381E57",
        "on-primary-fixed": "#231433",
        "surface-container-low": "#F8F3FA",
        "secondary-container": "#CBB5E2",
        "secondary-fixed": "#EBDDF2",
        "on-primary": "#ffffff",
        "tertiary": "#1e262a",
        "on-tertiary-fixed-variant": "#3f484c",
        "tertiary-container": "#333c40",
        "surface-bright": "#FAF7FC",
        "surface-tint": "#8362A5",
        "inverse-primary": "#CBB5E2",
        "on-secondary-fixed": "#231433",
        "on-secondary": "#ffffff",
        "surface-container-high": "#EADBF4",
        "outline": "#7F718B",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2D1843",
        "surface-container-highest": "#DFCBEA",
        "outline-variant": "#D6C2E5",
        "primary-container": "#5C3C7B",
        "on-tertiary-fixed": "#141d20",
        "on-background": "#231433",
        "secondary": "#8362A5",
        "primary-fixed-dim": "#CBB5E2",
        "on-error": "#ffffff",
        "surface-variant": "#DFCBEA",
        "secondary-fixed-dim": "#CBB5E2",
        "background": "#FAF7FC",
        "on-surface": "#231433"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "gutter": "16px",
        "margin-desktop": "32px",
        "md": "16px",
        "xs": "4px",
        "xl": "32px",
        "margin-mobile": "16px",
        "lg": "24px",
        "base": "4px"
      },
      fontFamily: {
        "headline-sm": ["Work Sans", "sans-serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "headline-lg-mobile": ["Work Sans", "sans-serif"],
        "headline-md": ["Work Sans", "sans-serif"],
        "display-lg": ["Work Sans", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
